### ISSUE TITLE
Bug or or no understanding of the method query?

### ISSUE THREAD

**Issue by abkrim** [dg/dibi#184]
On your manual

``` 
$result = dibi::query('SELECT * FROM users');
$value = $result->fetchSingle(); // single value
$all = $result->fetchAll(); // all rows
$assoc = $result->fetchAssoc('id'); // all rows as associative array
$pairs = $result->fetchPairs('customerID', 'name'); // all rows as key => value pairs
 ```

try and all actions ($result->fetchSingle(),$result->fetchAll(),...) return error

Only work (show Dibi
``` 
foreach ($result as $n => $row) {
    print_r($row);
}
 ```

Show 
```
DibiRow Object
(
    [job_id] => 2
    [user] => wikiis
    [start] => 1441355879
    [end] => 1441355921
    [path] => daily.0
    [id_master] => 2
)
```

$value = $result->fetchSingle();
$all = $result->fetchAll();

``` Uncaught exception 'DibiNotSupportedException' with message 'Cannot seek an unbuffered result set.```

Apreciate help.

**Comment by milo** [comment]
On which file:line is the exception thrown?

**Comment by abkrim** [comment]
```
$value = $result->fetchSingle(); // single value
```
Show 
```
Fatal error: Uncaught exception 'DibiNotSupportedException' with message 'Cannot seek an unbuffered result set.' in /Volumes/iDatos/abkrim/desarrollos/cprsync/vendor/dibi/dibi/dibi/drivers/DibiSqlite3Driver.php:345
Stack trace:
#0 /Volumes/iDatos/abkrim/desarrollos/cprsync/vendor/dibi/dibi/dibi/libs/DibiResult.php(117): DibiSqlite3Driver->seek(0)
#1 /Volumes/iDatos/abkrim/desarrollos/cprsync/vendor/dibi/dibi/dibi/libs/DibiResultIterator.php(52): DibiResult->seek(0)
#2 /Volumes/iDatos/abkrim/desarrollos/cprsync/app/Test/test_sqlite3.php(56): DibiResultIterator->rewind()
#3 {main}
  thrown in /Volumes/iDatos/abkrim/desarrollos/cprsync/vendor/dibi/dibi/dibi/drivers/DibiSqlite3Driver.php on line 345
```
The same message whet try

```
$value = $result->fetchAll();
```
Show 
```
Fatal error: Uncaught exception 'DibiNotSupportedException' with message 'Cannot seek an unbuffered result set.' in /Volumes/iDatos/abkrim/desarrollos/cprsync/vendor/dibi/dibi/dibi/drivers/DibiSqlite3Driver.php:345
Stack trace:
#0 /Volumes/iDatos/abkrim/desarrollos/cprsync/vendor/dibi/dibi/dibi/libs/DibiResult.php(117): DibiSqlite3Driver->seek(0)
#1 /Volumes/iDatos/abkrim/desarrollos/cprsync/vendor/dibi/dibi/dibi/libs/DibiResultIterator.php(52): DibiResult->seek(0)
#2 /Volumes/iDatos/abkrim/desarrollos/cprsync/app/Test/test_sqlite3.php(56): DibiResultIterator->rewind()
#3 {main}
  thrown in /Volumes/iDatos/abkrim/desarrollos/cprsync/vendor/dibi/dibi/dibi/drivers/Dibi

Apreciat help

**Comment by dg** [comment]
You can use fetchAll or foreach or fetchPairs, but not them all together. It is DB limitation.

**Comment by milo** [comment]
Part of the message 'unbuffered result set'  means, that you cannot rewind when you already stared iteration over the result. You have to run query again, it's the database limitation.

So, use:
/--php
$result = dibi::query('SELECT * FROM users');
$result->fetchAll();

$result = dibi::query('SELECT * FROM users');
$result->fetchSingle();
\--

**Comment by abkrim** [comment]
I don't understand.
```
$result = \dibi::query('SELECT * FROM jobs WHERE job_id=?',$job_id);
$result->fetchSingle();
```
or 
```
$result = \dibi::query('SELECT * FROM jobs WHERE job_id=?',$job_id);
$result->fetchAll(); 
```
show same DBIRow.

I must implent this? There aren't method for return array instead a object? 

Example.
my sql only must return on row...
```
$result = \dibi::query('SELECT * FROM jobs WHERE job_id=?',$job_id);
```

But $result it's a DBIrow, and I must to made a function for extract unique row and put on array.

**Comment by milo** [comment]
```php
# One scalar value (first column of first row)
$scalar = $result->fetchSingle();

# One DibiRow object (next row from result)
$row = $result->fetch();
$asArray = $row->toArray();  # converts DibiRow to array

# Array of DibiRow objects (all rows from result)
$rows = $result->fetchAll();
foreach ($rows as $row) {
    print_r($row);
    print_r($row->toArray());
}

# Iterate over the result
foreach ($result as $row) {
    print_r($row);
    print_r($row->toArray());
}
```
