### ISSUE TITLE
Return value of Dibi\Helpers::dump() must be of the type string, none returned

### ISSUE THREAD

**Issue by milo** [dg/dibi#256]
- bug report? yes
- version: f9bbc9fffb0e6c64f8f990b33d270925c73a1ad8

```
PHP Fatal error:  Uncaught TypeError: Return value of Dibi\Helpers::dump() must be of the type string, none returned in /home/milo/bidi-monitor/vendor/dibi/dibi/src/Dibi/Helpers.php:133
Stack trace:
#0 /home/milo/bidi-monitor/vendor/dibi/dibi/src/Dibi/Connection.php(231): Dibi\Helpers::dump(' \nINSERT INTO p...')
#1 /home/milo/bidi-monitor/src/grab.php(38): Dibi\Connection->test('INSERT INTO pow...', '127.0.0.1', '1', '-20.75')
#2 {main}
  thrown in /home/milo/bidi-monitor/vendor/dibi/dibi/src/Dibi/Helpers.php on line 133
```

Just quick report to not forget. Can send PR later.

**Comment by dg** [comment]
fixed

**Comment by milo** [comment]
Thanks for fix. I should reconsider using the word "later".

**Comment by dg** [comment]
:-)
